Repository gyapeee/desertwind, pull requests merged in 2022-01, with the labels that each got.

#17 Frontend init
  frontend/.browserslistrc
  frontend/.editorconfig
  frontend/.gitignore
  frontend/.vscode/extensions.json
  frontend/.vscode/launch.json
  frontend/.vscode/tasks.json
  frontend/README.md
  frontend/angular.json
  frontend/karma.conf.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.component.css
  frontend/src/app/app.component.html
  frontend/src/app/app.component.spec.ts
  frontend/src/app/app.component.ts
  frontend/src/app/app.module.ts
  frontend/src/assets/.gitkeep
  frontend/src/environments/environment.prod.ts
  frontend/src/environments/environment.ts
  frontend/src/favicon.ico
  frontend/src/index.html
  frontend/src/main.ts
  frontend/src/polyfills.ts
  frontend/src/styles.css
  frontend/src/test.ts
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.spec.json
Labels: frontend

#23 Added spring-boot-maven-plugin to have a runnable spring-boot in jar.
  .idea/encodings.xml
  pom.xml
Labels: deploy

#24 Merge deploy fix heroku
  .idea/encodings.xml
  pom.xml
  src/main/java/com/kodenigaz/desertwind/DesertWind.java
  src/main/java/com/kodenigaz/desertwind/Harmadik.java
  src/main/java/com/kodenigaz/desertwind/Hatodik.java
  src/main/java/com/kodenigaz/desertwind/Masodik.java
  src/main/java/com/kodenigaz/desertwind/Negyedik.java
  src/main/java/com/kodenigaz/desertwind/Otodik.java
  src/main/java/com/kodenigaz/desertwind/StringValues.java
Labels: backend, deploy
